Fix auto scroll pause in chat
marwanhawari/LeetRooms pull request #26
Opened 2023-04-23 07:47 UTC by smarttcoder

Hey, 
took care of this one, tested it
lemme know if u find any bugs

2023-04-24 01:08 UTC, marwanhawari requested changes

2023-04-24 01:08 UTC, marwanhawari commented on extension/src/components/Room.tsx
> +      };
You should use tailwind css styles.

2023-04-24 01:08 UTC, marwanhawari commented on extension/src/components/Room.tsx
> +    const [showNotification, setShowNotification] = useState(false);
do we need to use 2 state variables? Why can't we also just use `autoScroll` for determining when to show the notification?

2023-04-24 05:00 UTC, sachinsfo commented
you can close this pr, I created a new one

2025-04-30 21:04 UTC, marwanhawari commented
Closing stale PR

2025-04-30 21:04 UTC, closed without merging